[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ColorVectorSpace = "c3611d14-8923-5661-9e6a-0046d554d3a4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
GMT = "5752ebe1-31b9-557e-87aa-f909b540aa54"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
JSServe = "824d6782-a2ef-11e9-3a09-e5662e0c26f9"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RasterDataSources = "3cb90ccd-e1b6-4867-9617-4276c8b2ca36"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
RemoteS = "26020ff4-e92a-488e-a723-09c28e89e04a"

[compat]
PrettyTables = "2"